import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-white bg-gray-700 text-center text-3xl">
          Header part
        </h1>
        {children}
        <h1 className="text-white bg-green-800 text-center text-3xl">
          Footer part
        </h1>
      </body>
    </html>
  );
}
